[package]
name = "legado-reader"
version = "1.26.8293"
edition = "2021"

[lib]
name = "legado_reader_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
tauri-plugin-opener = "2"
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
reqwest = { version = "0.12", features = ["blocking", "cookies", "gzip", "brotli", "deflate", "charset"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
url = "2"
log = "0.4"
keyring = "4.1.6"
quick-xml = "0.38"
httpdate = "1"
rusqlite = { version = "0.32", features = ["bundled", "backup"] }
sha2 = "0.10"
percent-encoding = "2"
md5 = "0.7"
aes = "0.8"
des = "0.8"
cbc = { version = "0.1", features = ["alloc", "block-padding"] }
ecb = { version = "0.1", features = ["alloc", "block-padding"] }
cipher = { version = "0.4", features = ["alloc", "block-padding"] }
scraper = "0.24"
regex = "1"
jsonpath_lib = "0.3"
rquickjs = { version = "0.12.2", features = ["macro", "array-buffer"] }
base64 = "0.22"
